name: Back up Public Repositories

on:
  schedule:
    - cron: "45 11 * * 1" 
  workflow_dispatch:


env:
    GH_TOKEN: ${{ secrets.GH_BACKUP_TOKEN }}
jobs:
  back-up:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        public_repos:
          [
            "https://github.com/greyhoundforty/greyhoundforty.git",
            "https://github.com/greyhoundforty/ibmcloud-terraform-vpc-template-repo.git",
            "https://github.com/greyhoundforty/ryantiffany-dot-com-landing.git",
            "https://github.com/greyhoundforty/gh40-net.git",
            "https://github.com/greyhoundforty/ic-ce-action-test-repo.git",
            "https://github.com/greyhoundforty/gh-action-ibm-packer.git",
            "https://github.com/greyhoundforty/prjkt.git",
            "https://github.com/greyhoundforty/ibmcloud-devcontainer.git",
            "https://github.com/greyhoundforty/rt-dev.git",
            "https://github.com/greyhoundforty/github-action-ibmcloud-vpc-packer.git",
            "https://github.com/greyhoundforty/greyhoundforty.github.io.git",
            "https://github.com/cloud-design-dev/ibmcloud-vpc-awx.git",
            "https://github.com/cloud-design-dev/microk8s-ibmcloud-vpc.git",
            "https://github.com/cloud-design-dev/ibmcloud-python-template.git",
            "https://github.com/cloud-design-dev/ibmcloud-python-template.git",
            "https://github.com/cloud-design-dev/ibmcloud-ce-simple-app.git",
            "https://github.com/cloud-design-dev/ibmcloud-code-engine-github-action.git",
            "https://github.com/cloud-design-dev/ibmcloud-code-engine-demos.git",
            "https://github.com/cloud-design-dev/gh-webhook-function.git",
          ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install @larose/git-backup
        run: npm install -g @larose/git-backup

      - name: Back up public repositories 
        run: |
          git-backup snapshot \
            --repo ${{ matrix.public_repos }} \
            --remote ${{ vars.COS_ENDPOINT }}/${{ vars.COS_BUCKET }} \
            --access-key-id ${{ secrets.COS_ACCESS_KEY }} \
            --secret-access-key ${{ secrets.COS_SECRET_KEY }}

          git-backup prune \
            --repo ${{ matrix.public_repos }} \
            --remote ${{ vars.COS_ENDPOINT }}/${{ vars.COS_BUCKET }} \
            --access-key-id ${{ secrets.COS_ACCESS_KEY }} \
            --secret-access-key ${{ secrets.COS_SECRET_KEY }} \
            --retention-policy "daily=7"

      - name: Back up private streamlit repo 
        run: |
          git-backup snapshot \
            --repo "https://${{ env.GH_TOKEN }}@github.comgreyhoundforty/ibmcloud-vpc-streamlit.git", \
            --remote ${{ vars.COS_ENDPOINT }}/${{ vars.COS_BUCKET }} \
            --access-key-id ${{ secrets.COS_ACCESS_KEY }} \
            --secret-access-key ${{ secrets.COS_SECRET_KEY }}

          git-backup prune \
            --repo "https://${{ env.GH_TOKEN }}@github.comgreyhoundforty/ibmcloud-vpc-streamlit.git" \
            --remote ${{ vars.COS_ENDPOINT }}/${{ vars.COS_BUCKET }} \
            --access-key-id ${{ secrets.COS_ACCESS_KEY }} \
            --secret-access-key ${{ secrets.COS_SECRET_KEY }} \
            --retention-policy "daily=7"
            
      - name: Back up private ce spotify repo 
        run: |
          git-backup snapshot \
            --repo "https://${{ env.GH_TOKEN }}@github.comgreyhoundforty/ce-spotify-python.git", \
            --remote ${{ vars.COS_ENDPOINT }}/${{ vars.COS_BUCKET }} \
            --access-key-id ${{ secrets.COS_ACCESS_KEY }} \
            --secret-access-key ${{ secrets.COS_SECRET_KEY }}

          git-backup prune \
            --repo "https://${{ env.GH_TOKEN }}@github.comgreyhoundforty/ce-spotify-python.git" \
            --remote ${{ vars.COS_ENDPOINT }}/${{ vars.COS_BUCKET }} \
            --access-key-id ${{ secrets.COS_ACCESS_KEY }} \
            --secret-access-key ${{ secrets.COS_SECRET_KEY }} \
            --retention-policy "daily=7"
