name: Back up Public Repositories

on:
  schedule:
    - cron: "45 1 * * 1,4"
  workflow_dispatch:

env:
    GH_TOKEN: ${{ secrets.GH_BACKUP_TOKEN }}
jobs:
  back-up:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        public_repos:
          [
          "https://github.com/greyhoundforty/prefect-flow-testing.git",
          "https://github.com/greyhoundforty/prjkt.git",
          "https://github.com/greyhoundforty/ibmcloud-ansible-schematics.git",
          "https://github.com/greyhoundforty/demo-ocp-app.git",
          "https://github.com/greyhoundforty/512kb.club.git",
          "https://github.com/greyhoundforty/test-vpc-streamdeck.git",
          "https://github.com/greyhoundforty/gh40-net.git",
          "https://github.com/greyhoundforty/ic-ce-action-test-repo.git",
          "https://github.com/greyhoundforty/greyhoundforty.git",
          "https://github.com/greyhoundforty/gh-action-ibm-packer.git",
          "https://github.com/greyhoundforty/dts-sample-da.git",
          "https://github.com/greyhoundforty/ibmcloud-devcontainer.git",
          "https://github.com/greyhoundforty/rt-dev.git",
          "https://github.com/greyhoundforty/greyhoundforty.github.io.git",
          "https://github.com/greyhoundforty/IBM-Cloud-Ansible.git",
          "https://github.com/greyhoundforty/rtdev-lab-terraform.git",
          "https://github.com/greyhoundforty/katacoda-scenarios.git",
          "https://github.com/greyhoundforty/ibm-tf-backend-action-test.git",
          "https://github.com/greyhoundforty/checkpoint-iaas-mgmt-ibm-vpc.git",
          "https://github.com/greyhoundforty/simple-tekton-toolchain.git",
          "https://github.com/greyhoundforty/traefik-vpc-frontend.git",
          "https://github.com/greyhoundforty/schematics-pipeline-ansible-example.git",
          "https://github.com/greyhoundforty/code-engine-simple-api.git",
          "https://github.com/greyhoundforty/clouddatabases-helloworld-kubernetes-examples-1.git",
          "https://github.com/greyhoundforty/ibm_pxe_terraform.git",
          "https://github.com/greyhoundforty/two-zone-vpc.git"
          ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install @larose/git-backup
        run: npm install -g @larose/git-backup

      - name: Back up public repositories 
        run: |
          git-backup snapshot \
            --repo ${{ matrix.public_repos }} \
            --remote ${{ vars.COS_ENDPOINT }}/${{ vars.COS_BUCKET }} \
            --access-key-id ${{ secrets.COS_ACCESS_KEY }} \
            --secret-access-key ${{ secrets.COS_SECRET_KEY }}

          git-backup prune \
            --repo ${{ matrix.public_repos }} \
            --remote ${{ vars.COS_ENDPOINT }}/${{ vars.COS_BUCKET }} \
            --access-key-id ${{ secrets.COS_ACCESS_KEY }} \
            --secret-access-key ${{ secrets.COS_SECRET_KEY }} \
            --retention-policy "daily=7"
