name: Back up Public Repositories

on:
  schedule:
    - cron: "45 11 * * 1" 
  workflow_dispatch:


env:
    GH_TOKEN: ${{ github.token }}
jobs:
  back-up:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        public_repos:
          [
            "https://github.com/greyhoundforty/greyhoundforty",
            "https://github.com/greyhoundforty/ibmcloud-terraform-vpc-template-repo",
            "https://github.com/greyhoundforty/ryantiffany-dot-com-landing",
            "https://github.com/greyhoundforty/gh40-net",
            "https://github.com/greyhoundforty/ic-ce-action-test-repo",
            "https://github.com/greyhoundforty/gh-action-ibm-packer",
            "https://github.com/greyhoundforty/prjkt",
            "https://github.com/greyhoundforty/IBMCloud-Terraform-Examples",
            "https://github.com/greyhoundforty/ibmcloud-devcontainer",
            "https://github.com/greyhoundforty/terraform-ibm-awx",
            "https://github.com/greyhoundforty/rt-dev",
            "https://github.com/greyhoundforty/ibmcloud-classic-noos-25g",
            "https://github.com/greyhoundforty/github-action-ibmcloud-vpc-packer",
            "https://github.com/greyhoundforty/greyhoundforty.github.io",
            "https://github.com/greyhoundforty/IBM-Cloud-Ansible",
            "https://github.com/greyhoundforty/LunchSessions",
            "https://github.com/greyhoundforty/cloud-shell-scripts",
            "https://github.com/greyhoundforty/rtdev-lab-terraform",
            "https://github.com/greyhoundforty/rtshell-base",
            "https://github.com/greyhoundforty/rtshell",
            "https://github.com/greyhoundforty/postman-example-repo",
            "https://github.com/greyhoundforty/katacoda-scenarios",
            "https://github.com/greyhoundforty/ibm-tf-backend-action-test",
            "https://github.com/greyhoundforty/checkpoint-iaas-mgmt-ibm-vpc",
            "https://github.com/greyhoundforty/looking-glass-dev",
            "https://github.com/greyhoundforty/simple-tekton-toolchain",
            "https://github.com/greyhoundforty/traefik-vpc-frontend",
            "https://github.com/greyhoundforty/schematics-pipeline-ansible-example",
          ]
        # work_repos:
        #     [
        #       "https://github.com/cicd-excellence/app.git",
        #       "https://github.com/cicd-excellence/infra.git",
        #       "https://github.com/larose/cargo.git",
        #       "https://github.com/larose/conjugueur.git",
        #       "https://github.com/larose/eef.git",
        #       "https://github.com/larose/ena.git",
        #       "https://github.com/larose/git-backup-demo.git",
        #       "https://github.com/larose/pretty-printer.git",
        #       "https://github.com/larose/tsp.git",
        #       "https://github.com/larose/utt.git",
        #       "https://github.com/larose/verbes.git",
        #       "https://github.com/larose/yarn-monorepo-change-based-testing-demo.git",
        #       "https://github.com/larose/wiki.git",
        #     ]
  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install @larose/git-backup
        run: npm install -g @larose/git-backup

      - name: Back up personal public repositories
        run: |
          git-backup snapshot \
            --repo ${{ matrix.public_repos }} \
            --remote ${{ vars.COS_ENDPOINT }}/${{ vars.COS_BUCKET }} \
            --access-key-id ${{ secrets.COS_ACCESS_KEY }} \
            --secret-access-key ${{ secrets.COS_SECRET_KEY }}

          git-backup prune \
            --repo ${{ matrix.public_repos }} \
            --remote ${{ vars.COS_ENDPOINT }}/${{ vars.COS_BUCKET }} \
            --access-key-id ${{ secrets.COS_ACCESS_KEY }} \
            --secret-access-key ${{ secrets.COS_SECRET_KEY }} \
            --retention-policy "daily=7"
